name: Run PowerShell Script

on:
  push:
    branches: [ main ]

jobs:
  build:
    Name: Build_Cert
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PowerShell script
      shell: powershell
      run: |
        ./Web_Request2.ps1
