name: Run PowerShell Script

on:
  push:
    branches: [ main ]
    workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PowerShell script
      shell: powershell
      run: |
        ./Web_Request2.ps1
