name: Run PowerShell Script

on:
  repository_dispatch:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]


jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PowerShell script
      shell: powershell
      run: |
        ./Web_Request2.ps1
