name: Run PowerShell Script

on:
  repository_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  payload: ${{ toJSON(github.event.client_payload) }}
  business_unit: ${{ github.event.client_payload.additional_details.entity }}
  cert_subject: ${{ github.event.client_payload.additional_details.subject }}
  fn: ${{ github.event.client_payload.additional_details.fn }}
  sans: ${{ github.event.client_payload.additional_details.sans }}
  email: ${{ github.event.client_payload.additional_details.email }}
  ticket_number: ${{ github.event.client_payload.ritm_details.number }}
  snow_instance: ${{ github.event.client_payload.instance }}
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    
    steps:
      - name: Echo out the input variables
        run: |
          echo "client_payload: ${{ env.payload }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PowerShell script
        shell: powershell
        run: | 
          ./Web_Request2.ps1 -sub ${{ env.cert_subject }} -fn ${{ env.fn }} -sans_input ${{ env.sans }} -email ${{ env.email }}
